version: '2'
services:
  test_db:
    image: postgres
    volumes:
      - test-db-vol:/var/lib/postgresql
    ports:
      - "34000:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
      
volumes:
  test-db-vol:
    external: true